### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by kristiwalker** [DallasMorningNews/memorials#1]
**FRONT-END DESIGN/FUNCTIONALITY**
- [x] Make js for "add a pin" work
- [x] Fix height on mobile form
- [x] Make fake json
- [x] link json to 5 submissions
- [x] Add prev/next park nav functionality
- [x] Connect geojson to map pins
- [x] Connect map pins to right panel
- [x] Get coordinates of spot clicked (ask john if possible)
- [x] Get coordinates of center of screen (from inputting adress)
- [x] Popup that asks if you'd like to suggest this address (that the user searched)
- [x] Design race/ethnicity filters
- [x] Make race/ethnicity filters show respective pints/right-panel parks
- [ ] Add map color template styles

**BACK-END DESIGN/FUNCTIONALITY**
- [ ] Add edit window that copies info from respective user submission
- [ ] Add edit button for editing already edited submissions
- [ ] Figure out how to email DOM when new submission comes in

**NODE**
- [ ] Create models
- [ ] Add routes

**OPTIONAL**
- [ ] Smoother transitions for form
- [ ] Smoother transitions for pin button
- [ ] ADD A PIN slides in/out on hover?
- [ ] Modernize designs, styles, colors
- [ ] Custom map colors
